<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Supplier;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllSupplier(){


        return $this->getEntityManager()->getRepository(Supplier::class)->createQueryBuilder('s')
            ->orderBy('s.id')
            ->where('s.isImporter', 'Yes')
            ->getQuery()
            ->getResult();

    }
}
